collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.3322091
  rhythmicContrast: 1
  brandColors:
    - '#FFFFFF'
    - '#636363'
    - '#8C8C8C'
    - '#A7A7A8'
    - '#CBCBCD'
  lightness: 1
typography_spectrum: 0.2613828
navigation:
  - name: '>MOTION The experience'
    id: ed95a839-5685-4c8d-91eb-cf01ed444c43
    type: content
  - name: 'Content '
    id: 5d3d10db-9096-4f5d-bcb0-ace37c8ec8dd
    type: content
layout_spectrum: 0.3440135
name: '>MOTION London'
