layout_spectrum: 0.7103024
typography_spectrum: 0.406759
color:
  saturation: 0.7486785
  lightness: 0.2986242
  brandStrength: 0.3285617
  rhythmicContrast: 0.3982277
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: '>MOTION London'
