layout_spectrum: 0.17507768352515996
typography_spectrum: 0.15724137774668634
color:
  saturation: 0.6017120878677815
  brandStrength: 0.8682997180148959
  lightness: 0.37340171285904944
  brandColors:
    - '#EBEBED'
    - '#BFC8D9'
    - '#406578'
    - '#90ACC1'
    - '#1F3E52'
  rhythmicContrast: 0.7506513542030007
title: '>MOTION london'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Starts 2017
name: '>MOTIONlondon'
