collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5320405
  brandStrength: 0.3322091
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#636363'
    - '#8C8C8C'
    - '#A7A7A8'
    - '#CBCBCD'
  rhythmicContrast: 0
typography_spectrum: 0.2613828
layout_spectrum: 0.3220911
name: '>MOTION London'
