title: '>MOTION london'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6017120878677815
  brandStrength: 0.8682997180148959
  rhythmicContrast: 0.7506513542030007
  brandColors:
    - '#EBEBED'
    - '#BFC8D9'
    - '#406578'
    - '#90ACC1'
    - '#1F3E52'
  lightness: 0.3734017128590494
typography_spectrum: 0.1572413777466863
description: Launches early 2017
layout_spectrum: 0
name: '>MOTIONlondon'
