layout_spectrum: 0.8082041239831597
typography_spectrum: 0.9858011552132666
color:
  saturation: 1
  brandStrength: 0.3322091
  rhythmicContrast: 1
  brandColors:
    - '#FFFFFF'
    - '#636363'
    - '#8C8C8C'
    - '#A7A7A8'
    - '#CBCBCD'
  lightness: 1
name: '>MOTIONlondon'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: '>MOTION london'
description: Starts 2017
